import React, { useEffect, useState } from 'react';
import { Check, Clock3, MapPin, PackageCheck, RefreshCw, Truck, Warehouse } from 'lucide-react';
import { AuthUser, hasRole } from '../services/auth';
import { assignShipment, decideWarehouseBooking, getWarehouseBookings, receiveWarehouseInventory, reportWarehouseSpoilage, requestWarehouseBooking, releaseWarehouseInventory } from '../services/transactions';
import { getDeliveryTimeline, getLogisticsInventory, getLogisticsOptions, getLogisticsShipments, LogisticsInventory, LogisticsOptions, LogisticsShipment } from '../services/logistics';

interface Booking { id: number; warehouse_id: number; warehouse_name: string; farmer_name: string; quantity_kg: number; approved_quantity_kg: number | null; starts_on: string; ends_on: string | null; status: string; }

export const LogisticsCenter: React.FC<{ user: AuthUser }> = ({ user }) => {
  const isFarmer = hasRole(user, ['FARMER', 'FPO']);
  const isTransport = hasRole(user, ['TRANSPORT_PROVIDER']);
  const isWarehouse = hasRole(user, ['WAREHOUSE_MANAGER', 'ADMIN']);
  const isAdmin = hasRole(user, ['ADMIN']);
  const [options, setOptions] = useState<LogisticsOptions | null>(null);
  const [shipments, setShipments] = useState<LogisticsShipment[]>([]);
  const [inventory, setInventory] = useState<LogisticsInventory[]>([]);
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [booking, setBooking] = useState({ warehouseId: '', quantity: '', starts: '', ends: '', rate: '' });
  const [shipment, setShipment] = useState({ orderId: '', vehicleId: '', driverId: '', pickup: '', rate: '' });
  const [receive, setReceive] = useState({ bookingId: '', crop: '', quantity: '', grade: '', location: '', exit: '' });
  const [inventoryAction, setInventoryAction] = useState({ inventoryId: '', quantity: '', reason: '' });
  const [timeline, setTimeline] = useState<{ crop: string; farmer_name: string; buyer_name: string; shipment_status: string | null; scheduled_pickup_at: string | null; picked_up_at: string | null; delivered_at: string | null; events: Array<{ event_type: string; status: string | null; created_at: string }> } | null>(null);
  const [message, setMessage] = useState(''); const [error, setError] = useState('');

  const load = async () => {
    try {
      const [resourceData, shipmentData, inventoryData, bookingData] = await Promise.all([getLogisticsOptions(), getLogisticsShipments(), getLogisticsInventory(), getWarehouseBookings('ALL')]);
      setOptions(resourceData); setShipments(shipmentData); setInventory(inventoryData); setBookings((bookingData as Booking[]).filter((item) => item.status !== 'IN_STORAGE'));
    } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Unable to load logistics data'); }
  };
  useEffect(() => { void load(); }, []);
  const run = async (action: () => Promise<unknown>, success: string) => { setError(''); setMessage(''); try { await action(); setMessage(success); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Logistics request failed'); } };
  const warehouseRecord = options?.warehouses.find((item) => item.id === Number(booking.warehouseId));

  return <section className="border-y border-[#CFDFD1] bg-[#F7FAF7] py-8" id="logistics-center"><div className="mx-auto max-w-7xl space-y-5 px-4 sm:px-6 lg:px-8"><div className="flex items-center justify-between"><div><p className="text-sm font-black uppercase tracking-wider text-[#2D6A4F]">Logistics workspace</p><h2 className="text-3xl font-black text-stone-950">Move and store your crop</h2><p className="mt-1 text-sm font-bold text-stone-600">Named resources, capacity, rates, pickup status, and delivery history.</p></div><button type="button" onClick={() => void load()} className="inline-flex items-center gap-2 rounded-lg border border-stone-300 bg-white px-3 py-2 font-black"><RefreshCw className="h-4 w-4" /> Refresh</button></div>{message && <p className="rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{message}</p>}{error && <p className="rounded-xl bg-rose-50 p-3 text-sm font-bold text-rose-800">{error}</p>}
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{options?.warehouses.map((item) => <div key={item.id} className="rounded-2xl border border-stone-200 bg-white p-4"><div className="flex items-center gap-2"><Warehouse className="h-5 w-5 text-[#2D6A4F]" /><h3 className="font-black">{item.name}</h3></div><p className="mt-2 text-sm font-bold">Capacity: {item.capacity_kg.toLocaleString()} kg</p><p className="text-sm font-bold text-stone-600">Used: {item.used_capacity_kg.toLocaleString()} kg · Available: {item.available_capacity_kg.toLocaleString()} kg</p><p className="text-sm font-bold text-emerald-800">Storage rate: ₹{item.storage_rate_per_kg}/kg</p><p className="text-xs font-bold text-stone-500">{item.status}</p></div>)}</div>
    {isFarmer && <form className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm" onSubmit={(event) => { event.preventDefault(); void run(() => requestWarehouseBooking({ warehouse_id: Number(booking.warehouseId), quantity_kg: Number(booking.quantity), starts_on: booking.starts, ends_on: booking.ends || null, storage_rate_per_kg: warehouseRecord?.storage_rate_per_kg || Number(booking.rate) || 0 }), 'Warehouse request submitted.'); }}><div className="mb-3 flex items-center gap-2"><Warehouse className="h-5 w-5 text-[#2D6A4F]" /><h3 className="text-xl font-black">Request warehouse storage</h3></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="text-sm font-black">Warehouse<select required value={booking.warehouseId} onChange={(event) => setBooking({ ...booking, warehouseId: event.target.value })} className="mt-1 w-full rounded-lg border bg-white p-2"><option value="">Select warehouse</option>{options?.warehouses.map((item) => <option key={item.id} value={item.id}>{item.name} · ₹{item.storage_rate_per_kg}/kg</option>)}</select></label><label className="text-sm font-black">Quantity kg<input required type="number" min="0.001" value={booking.quantity} onChange={(event) => setBooking({ ...booking, quantity: event.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm font-black">Start<input required type="date" value={booking.starts} onChange={(event) => setBooking({ ...booking, starts: event.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm font-black">End<input type="date" value={booking.ends} onChange={(event) => setBooking({ ...booking, ends: event.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label><button className="self-end rounded-lg bg-[#165B33] px-4 py-2 font-black text-white">Request storage</button></div></form>}
      {(isFarmer || isTransport || isAdmin) && <form className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm" onSubmit={(event) => { event.preventDefault(); void run(() => assignShipment(Number(shipment.orderId), { vehicle_id: shipment.vehicleId ? Number(shipment.vehicleId) : null, driver_id: shipment.driverId ? Number(shipment.driverId) : null, scheduled_pickup_at: shipment.pickup || null, transport_rate_per_kg: shipment.rate ? Number(shipment.rate) : null }), 'Transport request assigned.'); }}><div className="mb-3 flex items-center gap-2"><Truck className="h-5 w-5 text-[#2D6A4F]" /><h3 className="text-xl font-black">Request or assign transport</h3></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="text-sm font-black">Crop order<select required value={shipment.orderId} onChange={(event) => setShipment({ ...shipment, orderId: event.target.value })} className="mt-1 w-full rounded-lg border bg-white p-2"><option value="">Select crop order</option>{options?.orders.map((order) => <option key={order.id} value={order.id}>{order.name}</option>)}</select></label><label className="text-sm font-black">Vehicle<select value={shipment.vehicleId} onChange={(event) => setShipment({ ...shipment, vehicleId: event.target.value })} className="mt-1 w-full rounded-lg border bg-white p-2"><option value="">Select vehicle</option>{options?.vehicles.filter((item) => item.is_available).map((item) => <option key={item.id} value={item.id}>{item.name} · {item.vehicle_type} · {item.provider_name}</option>)}</select></label><label className="text-sm font-black">Driver<select value={shipment.driverId} onChange={(event) => setShipment({ ...shipment, driverId: event.target.value })} className="mt-1 w-full rounded-lg border bg-white p-2"><option value="">Select driver</option>{options?.drivers.filter((item) => item.is_available).map((item) => <option key={item.id} value={item.id}>{item.name} · {item.provider_name}</option>)}</select></label><label className="text-sm font-black">Pickup time<input required type="datetime-local" value={shipment.pickup} onChange={(event) => setShipment({ ...shipment, pickup: event.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label><button className="self-end rounded-lg bg-[#165B33] px-4 py-2 font-black text-white">Assign transport</button></div></form>}
    {isWarehouse && <div className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-stone-200 bg-white p-5"><h3 className="mb-3 text-xl font-black">Booking status</h3>{bookings.length === 0 ? <p className="text-sm font-bold text-stone-500">No requested bookings.</p> : bookings.map((item) => <div key={item.id} className="mb-2 flex items-center justify-between gap-2 rounded-lg border p-3"><div><p className="font-black">{item.warehouse_name} · {item.farmer_name}</p><p className="text-xs font-bold text-stone-500">{item.quantity_kg} kg · {item.starts_on} · {item.status}</p></div>{item.status === 'REQUESTED' && <div className="flex gap-1"><button type="button" onClick={() => void run(() => decideWarehouseBooking(item.id, 'CONFIRMED'), 'Booking confirmed.')} className="rounded bg-[#165B33] px-2 py-1 text-xs font-black text-white"><Check className="h-3 w-3" /></button><button type="button" onClick={() => void run(() => decideWarehouseBooking(item.id, 'CANCELLED'), 'Booking cancelled.')} className="rounded border border-rose-300 px-2 py-1 text-xs font-black text-rose-700">Reject</button></div>}</div>)}</div><form className="rounded-2xl border border-stone-200 bg-white p-5" onSubmit={(event) => { event.preventDefault(); void run(() => receiveWarehouseInventory({ booking_id: Number(receive.bookingId), commodity_name: receive.crop, quantity_kg: Number(receive.quantity), quality_grade: receive.grade || undefined, storage_location: receive.location || undefined, expected_exit_date: receive.exit || undefined }), 'Inventory received.'); }}><h3 className="mb-3 text-xl font-black">Receive selected booking</h3><select required value={receive.bookingId} onChange={(event) => setReceive({ ...receive, bookingId: event.target.value })} className="w-full rounded-lg border bg-white p-2"><option value="">Select confirmed booking</option>{bookings.filter((item) => ['CONFIRMED', 'IN_STORAGE'].includes(item.status)).map((item) => <option key={item.id} value={item.id}>{item.warehouse_name} · {item.farmer_name} · {item.quantity_kg} kg</option>)}</select><input required placeholder="Crop name" value={receive.crop} onChange={(event) => setReceive({ ...receive, crop: event.target.value })} className="mt-2 w-full rounded-lg border p-2" /><input required type="number" placeholder="Quantity kg" value={receive.quantity} onChange={(event) => setReceive({ ...receive, quantity: event.target.value })} className="mt-2 w-full rounded-lg border p-2" /><input placeholder="Storage location" value={receive.location} onChange={(event) => setReceive({ ...receive, location: event.target.value })} className="mt-2 w-full rounded-lg border p-2" /><button className="mt-2 rounded-lg bg-[#165B33] px-4 py-2 font-black text-white">Receive stock</button></form></div>}
    <div className="rounded-2xl border border-stone-200 bg-white p-5"><div className="mb-3 flex items-center gap-2"><PackageCheck className="h-5 w-5 text-[#2D6A4F]" /><h3 className="text-xl font-black">Pickup and delivery timeline</h3></div>{shipments.length === 0 ? <p className="text-sm font-bold text-stone-500">No shipments yet.</p> : <div className="space-y-2">{shipments.slice(0, 8).map((item) => <button key={item.shipment_id} type="button" onClick={() => void getDeliveryTimeline(item.order_id).then(setTimeline).catch(() => setError('Unable to load delivery timeline'))} className="flex w-full items-center justify-between gap-3 rounded-lg border p-3 text-left"><span><strong>{item.crop}</strong> · {item.farmer_name} to {item.buyer_name}<br /><span className="text-xs font-bold text-stone-500">{item.vehicle_name || 'Vehicle pending'} · {item.driver_name || 'Driver pending'}</span></span><span className="rounded-full bg-stone-100 px-2 py-1 text-xs font-black">{item.status}</span></button>)}</div>}{timeline && <div className="mt-4 rounded-xl bg-stone-50 p-4"><p className="font-black">{timeline.crop} · {timeline.farmer_name} to {timeline.buyer_name}</p><p className="text-sm font-bold text-stone-600">Pickup: {timeline.scheduled_pickup_at ? new Date(timeline.scheduled_pickup_at).toLocaleString() : 'Not scheduled'} · Status: {timeline.shipment_status || 'Not assigned'}</p><div className="mt-2 space-y-1 text-xs font-bold text-stone-600">{timeline.events.map((event, index) => <p key={`${event.event_type}-${index}`}><Clock3 className="mr-1 inline h-3 w-3" />{event.event_type} · {event.status || 'Recorded'} · {new Date(event.created_at).toLocaleString()}</p>)}</div></div>}</div>
    <div className="rounded-2xl border border-stone-200 bg-white p-5"><h3 className="mb-3 text-xl font-black">Stored inventory</h3>{inventory.length === 0 ? <p className="text-sm font-bold text-stone-500">No inventory records.</p> : <div className="grid gap-2 md:grid-cols-2">{inventory.slice(0, 12).map((item) => <div key={item.inventory_id} className="rounded-lg border p-3"><p className="font-black">{item.crop} · {item.warehouse_name}</p><p className="text-sm font-bold text-stone-600">{item.quantity_kg} kg · {item.status} · {item.storage_location || 'Location pending'}</p><p className="text-xs font-bold text-stone-500">Exit: {item.expected_exit_date || 'Not scheduled'}</p>{isWarehouse && <div className="mt-2 flex gap-2"><button type="button" onClick={() => void run(() => reportWarehouseSpoilage(item.inventory_id, { quantity_kg: 1, reason: 'Recorded by warehouse operator' }), 'Spoilage recorded.')} className="rounded border border-rose-300 px-2 py-1 text-xs font-black text-rose-700">Spoilage</button><button type="button" onClick={() => void run(() => releaseWarehouseInventory(item.inventory_id, { quantity_kg: item.quantity_kg, reason: 'Released from selected inventory' }), 'Inventory released.')} className="rounded bg-[#165B33] px-2 py-1 text-xs font-black text-white">Release</button></div>}</div>)}</div>}</div>
  </div></section>;
};
