import React, { useState } from 'react';
import { Bell, FileCheck, Layers, Link2 } from 'lucide-react';
import { AuthUser, hasRole } from '../services/auth';
import { createMarketAlert, createPooledLot, getMarketMatches, submitBuyerVerification } from '../services/transactions';

export const MarketplaceGrowthCenter: React.FC<{ user: AuthUser }> = ({ user }) => {
  const isBuyer = hasRole(user, ['BUYER']);
  const isFpo = hasRole(user, ['FPO']);
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');
  const [document, setDocument] = useState({ type: '', reference: '', url: '' });
  const [lot, setLot] = useState({ fpoId: '', crop: '', farmerId: '', listingId: '', quantity: '', price: '', grade: '' });
  const [alert, setAlert] = useState({ crop: '', market: '', price: '', type: 'PRICE_TARGET' as 'PRICE_TARGET' | 'RECOMMENDATION_CHANGE' | 'DEMAND_MATCH' | 'OFFER_RECEIVED' });
  const [matchCrop, setMatchCrop] = useState('');
  const [matches, setMatches] = useState<Array<{ demand: Record<string, unknown>; matching_listings: Array<Record<string, unknown>> }>>([]);

  const run = async (action: () => Promise<unknown>, success: string) => {
    setError(''); setNotice('');
    try { await action(); setNotice(success); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Request failed'); }
  };

  return <section className="border-b border-[#CFDFD1] bg-[#EEF7EF] py-8"><div className="mx-auto max-w-7xl space-y-4 px-4 sm:px-6 lg:px-8"><div><p className="text-sm font-black uppercase tracking-wider text-[#2D6A4F]">Marketplace growth</p><h2 className="text-2xl font-black">Trust, aggregation, and proactive matching</h2></div>{notice && <p className="rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{notice}</p>}{error && <p className="rounded-xl bg-rose-50 p-3 text-sm font-bold text-rose-800">{error}</p>}<div className="grid gap-4 lg:grid-cols-2">
    {isBuyer && <div className="rounded-2xl border border-stone-200 bg-white p-5"><div className="mb-3 flex items-center gap-2"><FileCheck className="h-5 w-5 text-[#2D6A4F]" /><h3 className="font-black">Verify buyer account</h3></div><form className="space-y-2" onSubmit={(event) => { event.preventDefault(); void run(() => submitBuyerVerification({ document_type: document.type, document_reference: document.reference, document_url: document.url }), 'Verification document submitted for review.'); }}><input required placeholder="Document type" className="w-full rounded-lg border p-2" value={document.type} onChange={(event) => setDocument({ ...document, type: event.target.value })} /><input placeholder="Document reference" className="w-full rounded-lg border p-2" value={document.reference} onChange={(event) => setDocument({ ...document, reference: event.target.value })} /><input type="url" placeholder="Secure document URL" className="w-full rounded-lg border p-2" value={document.url} onChange={(event) => setDocument({ ...document, url: event.target.value })} /><button className="rounded-lg bg-[#165B33] px-4 py-2 font-black text-white">Submit verification</button></form></div>}
    {isFpo && <div className="rounded-2xl border border-stone-200 bg-white p-5"><div className="mb-3 flex items-center gap-2"><Layers className="h-5 w-5 text-[#2D6A4F]" /><h3 className="font-black">Create pooled FPO lot</h3></div><form className="grid gap-2 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); void run(() => createPooledLot({ fpo_id: Number(lot.fpoId), commodity_name: lot.crop, target_price_per_kg: lot.price ? Number(lot.price) : null, quality_grade: lot.grade || null, members: [{ farmer_user_id: lot.farmerId, listing_id: lot.listingId ? Number(lot.listingId) : null, quantity_kg: Number(lot.quantity) }] }), 'Pooled lot created.'); }}><input required type="number" placeholder="FPO ID" className="rounded-lg border p-2" value={lot.fpoId} onChange={(event) => setLot({ ...lot, fpoId: event.target.value })} /><input required placeholder="Crop" className="rounded-lg border p-2" value={lot.crop} onChange={(event) => setLot({ ...lot, crop: event.target.value })} /><input required placeholder="Member farmer UUID" className="rounded-lg border p-2" value={lot.farmerId} onChange={(event) => setLot({ ...lot, farmerId: event.target.value })} /><input required type="number" placeholder="Quantity kg" className="rounded-lg border p-2" value={lot.quantity} onChange={(event) => setLot({ ...lot, quantity: event.target.value })} /><input type="number" placeholder="Listing ID" className="rounded-lg border p-2" value={lot.listingId} onChange={(event) => setLot({ ...lot, listingId: event.target.value })} /><input type="number" placeholder="Target price / kg" className="rounded-lg border p-2" value={lot.price} onChange={(event) => setLot({ ...lot, price: event.target.value })} /><button className="rounded-lg bg-[#165B33] px-4 py-2 font-black text-white sm:col-span-2">Create pooled lot</button></form></div>}
    <div className="rounded-2xl border border-stone-200 bg-white p-5"><div className="mb-3 flex items-center gap-2"><Bell className="h-5 w-5 text-[#2D6A4F]" /><h3 className="font-black">Create market alert</h3></div><form className="grid gap-2 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); void run(() => createMarketAlert({ commodity_name: alert.crop || undefined, market_name: alert.market || undefined, target_price_per_kg: alert.price ? Number(alert.price) : null, alert_type: alert.type }), 'Market alert saved.'); }}><input placeholder="Crop" className="rounded-lg border p-2" value={alert.crop} onChange={(event) => setAlert({ ...alert, crop: event.target.value })} /><input placeholder="Market" className="rounded-lg border p-2" value={alert.market} onChange={(event) => setAlert({ ...alert, market: event.target.value })} /><input type="number" placeholder="Target price / kg" className="rounded-lg border p-2" value={alert.price} onChange={(event) => setAlert({ ...alert, price: event.target.value })} /><select className="rounded-lg border p-2" value={alert.type} onChange={(event) => setAlert({ ...alert, type: event.target.value as typeof alert.type })}><option value="PRICE_TARGET">Price target</option><option value="RECOMMENDATION_CHANGE">Recommendation changes</option><option value="DEMAND_MATCH">Demand match</option><option value="OFFER_RECEIVED">Offer received</option></select><button className="rounded-lg bg-[#165B33] px-4 py-2 font-black text-white sm:col-span-2">Save alert</button></form></div>
    <div className="rounded-2xl border border-stone-200 bg-white p-5"><div className="mb-3 flex items-center gap-2"><Link2 className="h-5 w-5 text-[#2D6A4F]" /><h3 className="font-black">Demand-to-listing matches</h3></div><form className="flex gap-2" onSubmit={(event) => { event.preventDefault(); void run(async () => { setMatches(await getMarketMatches(matchCrop || undefined)); }, 'Matching demands loaded.'); }}><input placeholder="Crop (optional)" className="min-w-0 flex-1 rounded-lg border p-2" value={matchCrop} onChange={(event) => setMatchCrop(event.target.value)} /><button className="rounded-lg border border-[#165B33] px-3 py-2 font-black text-[#165B33]">Match</button></form>{matches.length > 0 && <div className="mt-3 space-y-2 text-sm font-bold">{matches.slice(0, 3).map((match) => <p key={String(match.demand.id)}>Demand #{String(match.demand.id)}: {match.matching_listings.length} matching listing(s)</p>)}</div>}</div>
  </div></div></section>;
};
