import React, { useState } from 'react';
import { ClipboardCheck, CreditCard, FileWarning, PackageCheck, Scale, Search, Send, Warehouse } from 'lucide-react';
import {
  assignShipment,
  createBuyerDemand,
  getTransactionAudit,
  openDispute,
  recordFarmerProfit,
  requestWarehouseBooking,
  submitQualityInspection,
  transitionPayment,
} from '../services/transactions';
import { AuthUser, hasRole } from '../services/auth';

interface TransactionCenterProps { user: AuthUser }
const inputClass = 'mt-1 w-full rounded-lg border border-stone-300 px-3 py-2';

function Panel({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) {
  return <div className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><span className="text-[#2D6A4F]">{icon}</span><h3 className="text-lg font-black">{title}</h3></div>{children}</div>;
}

export const TransactionCenter: React.FC<TransactionCenterProps> = ({ user }) => {
  const isBuyer = hasRole(user, ['BUYER']);
  const isFarmer = hasRole(user, ['FARMER', 'FPO']);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [working, setWorking] = useState(false);
  const [demand, setDemand] = useState({ commodity_name: '', quantity_kg: '', target_price_per_kg: '', quality: '', delivery_location: '' });
  const [quality, setQuality] = useState({ listing_id: '', grade: 'A' as 'A' | 'B' | 'C' | 'REJECTED', notes: '' });
  const [warehouse, setWarehouse] = useState({ warehouse_id: '', quantity_kg: '', starts_on: '', ends_on: '', storage_rate_per_kg: '0' });
  const [payment, setPayment] = useState({ payment_id: '', status: 'PAYMENT_CONFIRMED' as 'PAYMENT_INITIATED' | 'PAYMENT_CONFIRMED' | 'ESCROWED' | 'RELEASED' | 'FAILED' | 'REFUNDED' });
  const [shipment, setShipment] = useState({ order_id: '', vehicle_id: '', driver_id: '', scheduled_pickup_at: '' });
  const [dispute, setDispute] = useState({ order_id: '', category: '', description: '' });
  const [profit, setProfit] = useState({ order_id: '', transport_cost: '0', storage_cost: '0', commission_cost: '0', wastage_cost: '0', other_cost: '0' });
  const [audit, setAudit] = useState({ entity_type: 'ORDER', entity_id: '' });

  const run = async (action: () => Promise<unknown>, success: string) => {
    setWorking(true); setError(null); setMessage(null);
    try { await action(); setMessage(success); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Transaction request failed'); } finally { setWorking(false); }
  };

  return <section className="border-y border-[#CFDFD1] bg-[#F7FAF7] py-8" id="transaction-center"><div className="mx-auto max-w-7xl space-y-5 px-4 sm:px-6 lg:px-8">
    <div><p className="text-sm font-black uppercase tracking-wider text-[#2D6A4F]">Transaction enablement</p><h2 className="text-3xl font-black text-stone-950">Complete the trade</h2><p className="mt-1 text-sm font-bold text-stone-600">Demand, quality, logistics, payment, disputes, and realized-profit records are connected to your account.</p></div>
    {message && <p className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{message}</p>}
    {error && <p className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-bold text-rose-800">{error}</p>}
    <div className="grid gap-5 lg:grid-cols-2">
      {isBuyer && <Panel title="Post buyer demand" icon={<Search className="h-5 w-5" />}><form className="grid gap-3 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); void run(() => createBuyerDemand({ commodity_name: demand.commodity_name, quantity_kg: Number(demand.quantity_kg), target_price_per_kg: demand.target_price_per_kg ? Number(demand.target_price_per_kg) : null, quality_requirements: { description: demand.quality }, delivery_location: demand.delivery_location }), 'Buyer demand published for farmer matching.'); }}><label className="text-sm font-black">Crop<input required className={inputClass} value={demand.commodity_name} onChange={(event) => setDemand({ ...demand, commodity_name: event.target.value })} /></label><label className="text-sm font-black">Quantity (kg)<input required type="number" min="1" className={inputClass} value={demand.quantity_kg} onChange={(event) => setDemand({ ...demand, quantity_kg: event.target.value })} /></label><label className="text-sm font-black">Target price / kg<input type="number" min="0" className={inputClass} value={demand.target_price_per_kg} onChange={(event) => setDemand({ ...demand, target_price_per_kg: event.target.value })} /></label><label className="text-sm font-black">Delivery location<input className={inputClass} value={demand.delivery_location} onChange={(event) => setDemand({ ...demand, delivery_location: event.target.value })} /></label><label className="text-sm font-black sm:col-span-2">Quality requirements<textarea className={inputClass} value={demand.quality} onChange={(event) => setDemand({ ...demand, quality: event.target.value })} /></label><button disabled={working} className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#165B33] px-4 py-2 font-black text-white sm:col-span-2"><Send className="h-4 w-4" /> Publish demand</button></form></Panel>}
      {(isFarmer || isBuyer) && <Panel title="Open a dispute" icon={<FileWarning className="h-5 w-5" />}><form className="space-y-3" onSubmit={(event) => { event.preventDefault(); void run(() => openDispute(Number(dispute.order_id), { category: dispute.category, description: dispute.description }), 'Dispute opened and recorded.'); }}><label className="text-sm font-black">Order ID<input required type="number" min="1" className={inputClass} value={dispute.order_id} onChange={(event) => setDispute({ ...dispute, order_id: event.target.value })} /></label><label className="text-sm font-black">Category<input required className={inputClass} placeholder="Quality, payment, delivery" value={dispute.category} onChange={(event) => setDispute({ ...dispute, category: event.target.value })} /></label><label className="text-sm font-black">Description<textarea required minLength={10} className={inputClass} value={dispute.description} onChange={(event) => setDispute({ ...dispute, description: event.target.value })} /></label><button disabled={working} className="rounded-lg border border-rose-300 px-4 py-2 font-black text-rose-700">Open grievance</button></form></Panel>}
      {isFarmer && <Panel title="Record quality grade" icon={<ClipboardCheck className="h-5 w-5" />}><form className="space-y-3" onSubmit={(event) => { event.preventDefault(); void run(() => submitQualityInspection(Number(quality.listing_id), { grade: quality.grade, notes: quality.notes }), 'Quality inspection recorded.'); }}><label className="text-sm font-black">Listing ID<input required type="number" min="1" className={inputClass} value={quality.listing_id} onChange={(event) => setQuality({ ...quality, listing_id: event.target.value })} /></label><label className="text-sm font-black">Grade<select className={inputClass} value={quality.grade} onChange={(event) => setQuality({ ...quality, grade: event.target.value as typeof quality.grade })}><option>A</option><option>B</option><option>C</option><option>REJECTED</option></select></label><label className="text-sm font-black">Inspection notes<textarea className={inputClass} value={quality.notes} onChange={(event) => setQuality({ ...quality, notes: event.target.value })} /></label><button disabled={working} className="rounded-lg bg-[#165B33] px-4 py-2 font-black text-white">Save grade</button></form></Panel>}
      {isFarmer && <Panel title="Book warehouse storage" icon={<Warehouse className="h-5 w-5" />}><form className="grid gap-3 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); void run(() => requestWarehouseBooking({ warehouse_id: Number(warehouse.warehouse_id), quantity_kg: Number(warehouse.quantity_kg), starts_on: warehouse.starts_on, ends_on: warehouse.ends_on || null, storage_rate_per_kg: Number(warehouse.storage_rate_per_kg) }), 'Warehouse booking requested.'); }}><label className="text-sm font-black">Warehouse ID<input required type="number" min="1" className={inputClass} value={warehouse.warehouse_id} onChange={(event) => setWarehouse({ ...warehouse, warehouse_id: event.target.value })} /></label><label className="text-sm font-black">Quantity (kg)<input required type="number" min="1" className={inputClass} value={warehouse.quantity_kg} onChange={(event) => setWarehouse({ ...warehouse, quantity_kg: event.target.value })} /></label><label className="text-sm font-black">Start date<input required type="date" className={inputClass} value={warehouse.starts_on} onChange={(event) => setWarehouse({ ...warehouse, starts_on: event.target.value })} /></label><label className="text-sm font-black">End date<input type="date" className={inputClass} value={warehouse.ends_on} onChange={(event) => setWarehouse({ ...warehouse, ends_on: event.target.value })} /></label><label className="text-sm font-black">Rate / kg<input type="number" min="0" className={inputClass} value={warehouse.storage_rate_per_kg} onChange={(event) => setWarehouse({ ...warehouse, storage_rate_per_kg: event.target.value })} /></label><button disabled={working} className="rounded-lg border border-[#165B33] px-4 py-2 font-black text-[#165B33] sm:col-span-2">Request storage</button></form></Panel>}
      <Panel title="Payment transition" icon={<CreditCard className="h-5 w-5" />}><form className="flex flex-wrap items-end gap-3" onSubmit={(event) => { event.preventDefault(); void run(() => transitionPayment(Number(payment.payment_id), { status: payment.status }), 'Payment status updated.'); }}><label className="text-sm font-black">Payment ID<input required type="number" min="1" className={inputClass} value={payment.payment_id} onChange={(event) => setPayment({ ...payment, payment_id: event.target.value })} /></label><label className="text-sm font-black">Status<select className={inputClass} value={payment.status} onChange={(event) => setPayment({ ...payment, status: event.target.value as typeof payment.status })}><option>PAYMENT_INITIATED</option><option>PAYMENT_CONFIRMED</option><option>ESCROWED</option><option>RELEASED</option><option>FAILED</option><option>REFUNDED</option></select></label><button disabled={working} className="rounded-lg bg-[#165B33] px-4 py-2 font-black text-white">Update payment</button></form></Panel>
      <Panel title="Assign transport" icon={<PackageCheck className="h-5 w-5" />}><form className="grid gap-3 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); void run(() => assignShipment(Number(shipment.order_id), { vehicle_id: shipment.vehicle_id ? Number(shipment.vehicle_id) : null, driver_id: shipment.driver_id ? Number(shipment.driver_id) : null, scheduled_pickup_at: shipment.scheduled_pickup_at || null }), 'Transport assignment recorded.'); }}><label className="text-sm font-black">Order ID<input required type="number" min="1" className={inputClass} value={shipment.order_id} onChange={(event) => setShipment({ ...shipment, order_id: event.target.value })} /></label><label className="text-sm font-black">Vehicle ID<input type="number" min="1" className={inputClass} value={shipment.vehicle_id} onChange={(event) => setShipment({ ...shipment, vehicle_id: event.target.value })} /></label><label className="text-sm font-black">Driver ID<input type="number" min="1" className={inputClass} value={shipment.driver_id} onChange={(event) => setShipment({ ...shipment, driver_id: event.target.value })} /></label><label className="text-sm font-black">Pickup time<input type="datetime-local" className={inputClass} value={shipment.scheduled_pickup_at} onChange={(event) => setShipment({ ...shipment, scheduled_pickup_at: event.target.value })} /></label><button disabled={working} className="rounded-lg border border-[#165B33] px-4 py-2 font-black text-[#165B33] sm:col-span-2">Assign transport</button></form></Panel>
      {isFarmer && <Panel title="Record realized profit" icon={<Scale className="h-5 w-5" />}><form className="grid gap-3 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); void run(() => recordFarmerProfit(Number(profit.order_id), { transport_cost: Number(profit.transport_cost), storage_cost: Number(profit.storage_cost), commission_cost: Number(profit.commission_cost), wastage_cost: Number(profit.wastage_cost), other_cost: Number(profit.other_cost) }), 'Realized profit recorded.'); }}><label className="text-sm font-black sm:col-span-2">Delivered order ID<input required type="number" min="1" className={inputClass} value={profit.order_id} onChange={(event) => setProfit({ ...profit, order_id: event.target.value })} /></label>{(['transport_cost', 'storage_cost', 'commission_cost', 'wastage_cost', 'other_cost'] as const).map((field) => <label key={field} className="text-sm font-black">{field.replaceAll('_', ' ')}<input type="number" min="0" className={inputClass} value={profit[field]} onChange={(event) => setProfit({ ...profit, [field]: event.target.value })} /></label>)}<button disabled={working} className="rounded-lg bg-[#165B33] px-4 py-2 font-black text-white sm:col-span-2">Save realized profit</button></form></Panel>}
      <Panel title="Transaction audit history" icon={<ClipboardCheck className="h-5 w-5" />}><form className="flex flex-wrap items-end gap-3" onSubmit={(event) => { event.preventDefault(); void run(async () => { const events = await getTransactionAudit(audit.entity_type, Number(audit.entity_id)); setMessage(`${events.length} audit events loaded for ${audit.entity_type} #${audit.entity_id}.`); }, 'Audit history loaded.'); }}><label className="text-sm font-black">Entity<select className={inputClass} value={audit.entity_type} onChange={(event) => setAudit({ ...audit, entity_type: event.target.value })}><option>ORDER</option><option>OFFER</option><option>PAYMENT</option><option>DISPUTE</option><option>LISTING</option></select></label><label className="text-sm font-black">ID<input required type="number" min="1" className={inputClass} value={audit.entity_id} onChange={(event) => setAudit({ ...audit, entity_id: event.target.value })} /></label><button disabled={working} className="rounded-lg border border-[#165B33] px-4 py-2 font-black text-[#165B33]">Load history</button></form></Panel>
    </div>
  </div></section>;
};
